 
                <div>
                    <h5 class="text-center">Commission Disclosure under SEBI Circular SEBI/IMD/CIR No.4 /168230/09
                    </h5>
                    <p class="text-center">The details of the commission earned by us from various Asset Management
                        Companies (AMCs) are as
                        below:</p>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Scheme Type </th>
                                <th>Trail 1st Year</th>
                                <th>Trail 2nd Year Onwards</th>
                            </tr>
                        </thead>
                        <?php $commissionData = [
							[ 'Scheme'   => 'Arbitrage Funds', 'trail1st'   => '0.05% to 0.60%', 'trail2nd'   => '0.05% to 0.60%', ],
							[ 'Scheme'   => 'ELSS Funds', 'trail1st'   => '0.50% to 1.25%', 'trail2nd'   => '0.50% to 1.25%', ],
							[ 'Scheme'   => 'Equity Oriented Funds', 'trail1st'   => '0.50% to 1.25%', 'trail2nd'   => '0.50% to 1.25%', ],
							[ 'Scheme'   => 'Aggressive Hybrid Equity Funds', 'trail1st'   => '0.50% to 1.25%', 'trail2nd'   => '0.50% to 1.25%', ],
							[ 'Scheme'   => 'Fixed Maturity Plans', 'trail1st'   => '0.05% to 0.50%', 'trail2nd'   => '0.05% to 0.50%', ],
							[ 'Scheme'   => 'Fund of Funds', 'trail1st'   => '0.25% to 1%', 'trail2nd'   => '0.25% to 1%', ],
							[ 'Scheme'   => 'Gilt Funds', 'trail1st'   => '0.25% to 1%', 'trail2nd'   => '0.05% to 0.65%', ],
							[ 'Scheme'   => 'Hybrid Debt Funds', 'trail1st'   => '0.05% to 0.75%', 'trail2nd'   => '0.05% to 0.75%', ],
							[ 'Scheme'   => 'Income Funds', 'trail1st'   => '0,05% to 1%', 'trail2nd'   => '0,05% to 1%', ],
							[ 'Scheme'   => 'Index Funds', 'trail1st'   => '0.01% to 0.75%', 'trail2nd'   => '0.01% to 0.75%', ],
							[ 'Scheme'   => 'Liquid Funds / Ultra Short-Term Funds', 'trail1st'   => '0.05% to 0.50%', 'trail2nd'   => '0.05% to 0.50%', ],
							[ 'Scheme'   => 'Short-Term Income Funds', 'trail1st'   => '0.05% to 0.65%', 'trail2nd'   => '0.05% to 0.65%', ],
							[ 'Scheme'   => 'Thematic / Sector Funds', 'trail1st'   => '0.50% to 1.25%', 'trail2nd'   => '0.50% to 1.25%', ],
						];?>
                        <tbody>
                            <?php foreach($commissionData as $commissionitems){?>
                            <tr>
                                <td><?=  $commissionitems['Scheme'];?></td>
                                <td><?=  $commissionitems['trail1st'];?></td>
                                <td><?=  $commissionitems['trail2nd'];?></td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <p class="pt-3  test-left">*Investments in mutual funds are subject to market risk and
                        customers should
                        read the scheme-related documents / key information documents of the Mutual Fund products
                        carefully before investing. This is on a best-effort basis and rates are updated as and when
                        actual rates are received from AMCs. This is for information purposes only and does not
                        represent any financial or other advice. The information contained in this presentation is
                        general in nature. The client acknowledges that the prices and net asset values of the
                        mutual
                        fund schemes are subject to fluctuation based on the factors and the forces affecting the
                        capital markets. Past performance of the sponsors, mutual funds, or their affiliates do not
                        indicate or guarantee the future performance of any scheme in any manner, and historical
                        performance, when presented, is purely for reference purposes. This page is an integral part
                        of
                        the document generated by us. Investment proposals are prepared on request of the client for
                        general information and reference purposes. It aims to demonstrate a proposal considering
                        the
                        client’s investment objective and investment preferences designed based on information
                        provided
                        by the client. The proposal is purely on a non-binding basis and the client is free to
                        accept or
                        reject the proposal. We shall not be held responsible for any direct or indirect loss caused
                        by
                        relying on this information. The client is free to seek the opinion of the legal,
                        investment,
                        and taxation advisor for making investment decisions. </p>
                </div>
            